---
title: "What is 'Apparent Temperature'?"
description: "What the heck is AT?"
author: "Pedram Fard and Chirag Patel"
date: "1/14/2024"
date-modified: "1/14/2024"
categories:
  - apparent temperature
---

In a [few](./intro_gridex.html) [of](./extreme_heat_california.html) our posts, we talk a lot about "**apparent temperature**". What is it and how is it calculated?

While different measures have been developed in epidemiological research to quantify heat and cold exposure, a composite is a solution for extreme heat and cold exposure assessment.

We used the apparent temperature (AT) as it allows for a holistic representation of thermal comfort and perceived temperature by incorporating factors such as relative humidity and wind speed in addition to the ambient temperature.

AT is derived through a linear combination of actual temperature, vapor pressure and wind speed in metric units and interpreted in Celsius (°C), where:

$AT = −2.7 + 1.04T + 2.0P − 0.65u$

AT: Apparent Temperature Index in °C\
T: Temperature in °C\
P: Vapor pressure in kPa\
u: Wind speed in m/s

## References

[Spangler KR, Liang S, Wellenius GA. Wet-Bulb Globe Temperature, Universal Thermal Climate Index, and Other Heat Metrics for US Counties, 2000–2020. Scientific Data. 2022 Jun 17;9(1):1–9.](http://paperpile.com/b/r994tT/XWgx)

[Steadman RG. A Universal Scale of Apparent Temperature. J Appl Meteorol Climatol. 1984 Dec 1;23(12):1674–87.](http://paperpile.com/b/r994tT/ZmjT)

[Sheridan SC, Lee CC, Allen MJ. The Mortality Response to Absolute and Relative Temperature Extremes. Int J Environ Res Public Health \[Internet\]. 2019 Apr 27;16(9). Available from:](http://paperpile.com/b/r994tT/josx)<http://dx.doi.org/10.3390/ijerph16091493>
